### ISSUE TITLE
API Enhancement Request - Spot_Sessions

### ISSUE THREAD

**Issue by Logiqx** [djong1/gp3s#21]
It would be extremely useful to have a Spot_Sessions method on the GP3S API.

This will allow my Python script that checks event rankings to also check the spot rankings for ghost speeds, etc.

Two parameters would make sense for a Spot_Sessions method on the GP3S API:
- id
- year

**Comment by djong1** [comment]
@Logiqx I have implemented a beta version, can you validate? Year filter is not implemented, including top xx, so you get the top 100 best sessions for now.

**Comment by Logiqx** [comment]
I quickly tried it via the web and got a 404:

![image](https://github.com/djong1/gp3s/assets/17449078/6ce8f757-019f-4fe6-973c-650b63a9a1f4)

**Comment by djong1** [comment]
@Logiqx can you give it a try?

**Comment by Logiqx** [comment]
@djong1 - I'm still getting a 404 for GPS-Speedsurfing-API-v2

GPS-Wingfoiling-API-v2 and GPS-Foilsurfing-API-v2 are returning results.

I think that the "speedtype" is probably redundant?

Do you propose to allow "top" to be set to zero for all results, or some kind a pagination?

**Comment by djong1** [comment]
@Logiqx I have fixed a couple of things, but I need your advise: we will expose the spot session API only via the "professional" user tier. However I'm still reluctant to do this because we get more and more request from users to hide their data, so we are also building a option to hide your postings and make it only visible amongst friends. While working on this feature it does not feel right to expose all possible sessions via an API where I cannot control the consumer. Is somebody is scraping the website at least I have a valid e-mail and a payment statement to track the user for policy violation. 

What would be the best way to tackle this in a way that you can do your job and that we are careful with user session data? For now I have limited the api to only the best 100 sessions per spot.
